[project]
name = "spdatalab"
version = "0.1.0"
description = "Spatial‑Data‑Lab scaffold"
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
Homepage = "https://example.com"

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"