version: '3.9'
services:
  local_pg:
    image: postgis/postgis:16-3.4
    ports: ['5432:5432']
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks: [app_net]

  pgadmin:
    image: dpage/pgadmin4
    ports: ['5050:80']
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on: [local_pg]
    networks: [app_net]

  workspace:
    build: ..
    env_file:
      - ../.env
    volumes:
      - ..:/workspace
    working_dir: /workspace
    depends_on: [local_pg]
    command: tail -f /dev/null
    networks: [app_net]

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/24